[package]
name = "cdumay_error"
version = "0.1.5"
authors = ["Cédric Dumay <cedric.dumay@gmail.com>"]
license = "MIT"
readme = "README.md"
documentation = "https://docs.rs/cdumay_errors"
repository = "https://github.com/cdumay/rust-cdumay_errors"
homepage =  "https://github.com/cdumay/rust-cdumay_errors"
description = "A library to serialize and deserialize error using serde"
keywords = ["Error", "serde"]
categories = ["caching", "data-structures", "encoding"]

[badges]
gitlab = { repository = "cdumay/rust-cdumay_errors" }
travis-ci = { repository = "cdumay/rust-cdumay_errors" }
maintenance = { status = "as-is" }

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde-value = "0.6"